USUARIOS = [
    {'id':1,
    'username':'reinel',
     'password':'quiz'
     },
     {'id':2,
    'username':'james',
     'password':'jajaja'
     },
     {'id':3,
    'username':'johan',
     'password':'pina'
     },
     {'id':4,
    'username':'camilo',
     'password':'1234'
     },
     {'id':5,
    'username':'chatgpt',
     'password':'version4'
     }
]